### ISSUE TITLE
Solution won't open with VS2015

### ISSUE THREAD

**Issue by fallenidol** [0xFireball/PenguinUpload#19]
Solution won't open with VS2015. Looks like vs2017 is required?

PenguinUpload.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by 0xFireball** [comment]
Yes, VS2017 is required. I just upgraded it yesterday; Microsoft is dropping the old `project.json` tooling. I held on to it for as long as I could, but I just decided I'd start using the latest CLI tools, which don't support `project.json`. You can still build with any command line tools version that supports the new `.csproj` format. But if you want VS, you'll have to use VS2017 because Microsoft hasn't added the new `.csproj` .NET Standard support to VS2015.

**Comment by fallenidol** [comment]
No worries. I just learned that vs2017 community edition is essentially professional edition which is pretty cool.
